# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-02 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
