# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-02 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stars',
        ),
    ]
